### ISSUE TITLE
webpack public path problem

### ISSUE THREAD

**Issue by mk2** [re-fort/vue-webpack-boilerplate#49]
I have encountered the following problem.
My project (https://github.com/my-lgtm/my-lgtm.github.com) use the github pages, so the published address is "https://my-lgtm.github.io". Therefore, I set webpack `_project` to `''`(empty string). But vue-webpack-boilerplate use `/${_project}/` as webpack publicpath (in production), so my build stylesheets were reading the font-awesome from `http://static/..`. (Also you know, `//` was interpreted `http(s)://`.)
Finally I set `` to `_project` and `/` to publicpath, and got the correct font-awesome path.

There is any better solution?

**Comment by re-fort** [comment]
Thanks for getting in touch and sorry for confusing you.
Since my website is hosted with custom domain on GitHub pages, setting public path with condition is needed for me.
But, including you, most of people may not be needed it.

So it would be good to be able to set public path with enviroment variable.
I'll fix it in this weekend!

**Comment by re-fort** [comment]
I found the more smart solution.
Refer to my PR for checking the changes(#50).

**Comment by mk2** [comment]
Thank, it works very well, and smartest solution!
